CC      = gcc
C_FLAGS = -Wall -g3 -ggdb3 -O
L_FLAGS = -lz -lcrypt -lpthread -lm

O_FILES = act_comm.o act_info.o act_move.o act_obj.o act_wiz.o bit.o mccp.o mc_mem.o\
	board.o build.o clan.o comm.o daemon.o db.o angel.o x-socials.o detox.o\
	demon.o drow.o fight.o kav_wiz.o handler.o kav_fight.o kav_info.o \
	interp.o mage.o magic.o mem.o monk.o monk2.o ninja.o olc.o upgrade.o \
	olc_act.o olc_save.o save.o special.o string.o arena.o dragon.o \
	update.o vamp.o ww.o shapeshifter.o tanarri.o undead_knight.o social-edit.o\
        samurai.o wizutil.o const.o spiderdroid.o lich.o jope.o auction.o \
        jobo_king.o jobo_data.o jobo_fight.o jobo_act.o jobo_wiz.o jobo_util.o \
        devik.o maar.o runemaster.o economy.o seth.o drunk.o wizlist.o recycle.o\
	mathproxy.o change.o elf.o kahn.o imm_spec.o desc_map.o wizard.o huto.o chrono.o\
        rpalign.o psycho.o vote.o sob.o rponly.o military.o phoenix.o randomeq.o\
        wraith.o

dystopia: $(O_FILES)
	rm -f dystopia
	chmod g+w $(O_FILES)
	$(CC)  -o dystopia -g3 -ggdb3 $(O_FILES) $(L_FLAGS)

.c.o: merc.h
	$(CC) -c $(C_FLAGS) $<

clean :
	rm -f *.o ; rm -f dystopia
